export const GET_REGIONS_START = 'GET_REGIONS_START';
export const GET_REGIONS_SUCCESS = 'GET_REGIONS_SUCCESS';
export const GET_REGIONS_FAILURE = 'GET_REGIONS_FAILURE';

export const ADD_REGION_START = 'ADD_REGION_START';
export const ADD_REGION_SUCCESS = 'ADD_REGION_SUCCESS';
export const ADD_REGION_FAILURE = 'ADD_REGION_FAILURE';
